### ISSUE TITLE
SI Fast Corrector Model02 Simulation

### ISSUE THREAD

**Issue by LuanaVilela** [lnls-ima/si-fast-correctors#1]
CH:
 si-fast-correctors/model-02/simulation/2017-01-05_SI_FC_Model02_Sim_X=-12_12mm_Z=-250_250mm_Ich=1A.txt 

CV:
 si-fast-correctors/model-02/simulation/2017-01-05_SI_FC_Model02_Sim_X=-12_12mm_Z=-250_250mm_Icv=1A.txt 

QS:
 si-fast-correctors/model-02/simulation/2017-01-05_SI_FC_Model02_Sim_X=-12_12mm_Z=-250_250mm_Iqs=3A.txt 

QS + CH + CV:
 si-fast-correctors/model-02/simulation/2017-01-05_SI_FC_Model02_Sim_X=-12_12mm_Z=-250_250mm_Iqs=3A_Ich=1A_Icv=1A.txt

**Comment by xresende** [comment]
analysis of CH, CV and QS fieldmaps done. (still missing combined functions).
multipoles are relatively large. but absolute residual fields (kicks) are small.
approval for model 02 fast correctors are pending: dynamical aperture calculations should be performed.
