### ISSUE TITLE
Added new model (Model 06)

### ISSUE THREAD

**Issue by LuanaVilela** [lnls-ima/si-fast-correctors#4]
Added new fieldmaps for SI fast correctors (Model 06):

si-fast-correctors/model-06/simulation/magnetic/

**Comment by xresende** [comment]
fmaps analysed. they are all ok.
@LuanaVilela , please check if we need to update magnet drawing in sirius wiki pages.

**Comment by LuanaVilela** [comment]
The drawings have been updated!
